// // StructureAnalyzerTests.cs
// // Copyright © 2012–Present Jackalope Technologies, Inc. and Doug Gerard.
// // Use subject to the MIT License.

#region Usings

using CodeStructure.Analyzers.Diagnostics;
using CodeStructure.Analyzers.Structure;
using Microsoft.CodeAnalysis;

#endregion

namespace CodeStructure.Analyzers.Tests;

public sealed class StructureAnalyzerTests
{
    [Fact]
    public async Task STR0001_FlagsContinueStatement()
    {
        var source = @"
class C
{
    void M()
    {
        for (int i = 0; i < 10; i++)
        {
            {|#0:continue;|}
        }
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0001NoContinueAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0001, locationIndex: 0)
            );
    }

    [Fact]
    public async Task STR0001_IgnoresGeneratedCode()
    {
        var source = @"
// <auto-generated/>
class C
{
    void M()
    {
        for (int i = 0; i < 10; i++)
        {
            continue;
        }
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0001NoContinueAnalyzer>(source);
    }

    [Fact]
    public async Task STR0001_RespectsEditorConfigDisabled()
    {
        var source = @"
class C
{
    void M()
    {
        for (int i = 0; i < 10; i++)
        {
            continue;
        }
    }
}
";

        var editorConfig = @"
root = true

[*.cs]
dotnet_diagnostic.STR0001.severity = none
";

        await AnalyzerTestUtilities.VerifyAnalyzerWithConfigAsync<Str0001NoContinueAnalyzer>(source, editorConfig);
    }

    [Fact]
    public async Task STR0002_FlagsMultipleReturns()
    {
        var source = @"
class C
{
    int M(int value)
    {
        if (value > 0)
        {
            {|#0:return 1;|}
        }

        return 2;
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0002MultipleReturnsAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0002, locationIndex: 0)
            );
    }

    [Fact]
    public async Task STR0003_FlagsReturnInVoidMethod()
    {
        var source = @"
class C
{
    void M(int value)
    {
        if (value == 0)
        {
            {|#0:return;|}
        }
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0003ReturnInVoidMethodAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0003, locationIndex: 0)
            );
    }

    [Fact]
    public async Task STR0004_FlagsLongIfElseChain()
    {
        var source = @"
class C
{
    int M(int value)
    {
        {|#0:if|} (value == 0)
        {
            return 1;
        }
        else if (value == 1)
        {
            return 2;
        }
        else if (value == 2)
        {
            return 3;
        }
        else
        {
            return 4;
        }
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0004IfElseChainsAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0004, locationIndex: 0, "4")
            );
    }

    [Fact]
    public async Task STR0004_FlagsIfElseChainWithNonLiteral()
    {
        var source = @"
class C
{
    int M(int value)
    {
        {|#0:if|} (value > 0)
        {
            return 1;
        }
        else if (value > 1)
        {
            return 2;
        }
        else if (value > 2)
        {
            return 3;
        }
        else
        {
            return 4;
        }
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0004IfElseChainsAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0004, locationIndex: 0, "4")
            );
    }

    [Fact]
    public async Task STR0005_FlagsReturnInNestedBlock()
    {
        var source = @"
class C
{
    int M(int value)
    {
        if (value == 1)
        {
            {|#0:return 2;|}
        }

        return 3;
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0005ReturnInNestedBlockAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0005, locationIndex: 0, "if statement")
            );
    }

    [Fact]
    public async Task STR0006_FlagsElseIf()
    {
        var source = @"
class C
{
    int M(int value)
    {
        if (value == 0)
        {
            return 1;
        }
        {|#0:else|} if (value == 1)
        {
            return 2;
        }

        return 3;
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0006NoElseIfAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0006, locationIndex: 0)
            );
    }

    [Fact]
    public async Task STR0006_FlagsElseIfWithMixedTargets()
    {
        var source = @"
class C
{
    int M(int value, int other)
    {
        if (value == 0)
        {
            return 1;
        }
        {|#0:else|} if (other == 1)
        {
            return 2;
        }

        return 3;
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0006NoElseIfAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0006, locationIndex: 0)
            );
    }

    [Fact]
    public async Task STR0006_FlagsElseIfInTopLevelStatements()
    {
        var source = @"
int value = 1;

if (value == 0)
{
}
{|#0:else|} if (value == 1)
{
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerWithOutputKindAsync<Str0006NoElseIfAnalyzer>(source,
                 OutputKind.ConsoleApplication,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0006, locationIndex: 0)
            );
    }

    [Fact]
    public async Task STR0007_FlagsSuspiciousRegion()
    {
        var source = @"
class C
{
    {|#0:#region TODO|}
    void M() { }
    #endregion
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0007SuspiciousRegionsAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0007, locationIndex: 0, "TODO")
            );
    }

    [Fact]
    public async Task STR0008_FlagsMultipleTypes()
    {
        var source = @"
class A
{
}

class {|#0:B|}
{
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0008OneTypePerFileAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0008, locationIndex: 0)
            );
    }

    [Fact]
    public async Task STR0008_FlagsMultipleTypesInFileScopedNamespace()
    {
        var source = @"
namespace Sample;

class A
{
}

class {|#0:B|}
{
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0008OneTypePerFileAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0008, locationIndex: 0)
            );
    }

    [Fact]
    public async Task STR0008_FlagsMultipleRecords()
    {
        var source = @"
record A;

record {|#0:B|};
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0008OneTypePerFileAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0008, locationIndex: 0)
            );
    }

    [Fact]
    public async Task STR0008_AllowsNestedTypes()
    {
        var source = @"
class Outer
{
    class Inner
    {
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0008OneTypePerFileAnalyzer>(source);
    }

    [Fact]
    public async Task STR0009_FlagsNestingDepthWarning()
    {
        var source = @"
class C
{
    void M()
    {
        if (true)
        {
            if (true)
            {
                if (true)
                {
                    {|#0:if (true)
                    {
                    }|}
                }
            }
        }
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0009NestingDepthAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0009, locationIndex: 0, "4", "3")
            );
    }

    [Fact]
    public async Task STR0009_AllowsDepthAtLimit()
    {
        var source = @"
class C
{
    void M()
    {
        if (true)
        {
            if (true)
            {
                if (true)
                {
                }
            }
        }
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0009NestingDepthAnalyzer>(source);
    }

    [Fact]
    public async Task STR0009_FlagsNestingDepthError()
    {
        var source = @"
class C
{
    void M()
    {
        if (true)
        {
            if (true)
            {
                if (true)
                {
                    {|#0:if (true)
                    {
                        {|#1:if (true)
                        {
                            {|#2:if (true)
                            {
                                {|#3:if (true)
                                {
                                }|}
                            }|}
                        }|}
                    }|}
                }
            }
        }
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0009NestingDepthAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0009, locationIndex: 0, "4", "3"),
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0009, locationIndex: 1, "5", "3"),
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0009, locationIndex: 2, "6", "3"),
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0009Error, locationIndex: 3, "7", "6")
            );
    }

    [Fact]
    public async Task STR0009_FlagsAcrossUsingAndLock()
    {
        var source = @"
using System.IO;

class C
{
    void M()
    {
        if (true)
        {
            using (var stream = new MemoryStream())
            {
                lock (this)
                {
                    {|#0:switch (1)
                    {
                        case 1:
                            break;
                    }|}
                }
            }
        }
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0009NestingDepthAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0009, locationIndex: 0, "4", "3")
            );
    }

    [Fact]
    public async Task STR0009_FlagsAcrossTryCatch()
    {
        var source = @"
class C
{
    void M()
    {
        if (true)
        {
            if (true)
            {
                try
                {
                    {|#0:if (true)
                    {
                    }|}
                }
                catch
                {
                }
            }
        }
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0009NestingDepthAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0009, locationIndex: 0, "4", "3")
            );
    }

    [Fact]
    public async Task STR0010_FlagsMissingArgumentValidation()
    {
        var source = @"
class C
{
    public void M(string {|#0:value|})
    {
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0010MissingArgumentValidationAnalyzer>(source,
                 AnalyzerTestUtilities.CreateResult(DiagnosticDescriptors.STR0010, locationIndex: 0, "M", "value")
            );
    }

    [Fact]
    public async Task STR0010_AllowsThrowIfNull()
    {
        var source = @"
using System;

class C
{
    public void M(string value)
    {
        ArgumentNullException.ThrowIfNull(value);
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0010MissingArgumentValidationAnalyzer>(source);
    }

    [Fact]
    public async Task STR0010_AllowsThrowIfNullOrWhiteSpace()
    {
        var source = @"
using System;

class C
{
    public void M(string value)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(value);
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0010MissingArgumentValidationAnalyzer>(source);
    }

    [Fact]
    public async Task STR0010_AllowsThrowIfNullOrEmpty()
    {
        var source = @"
using System;

class C
{
    public void M(string value)
    {
        ArgumentException.ThrowIfNullOrEmpty(value);
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0010MissingArgumentValidationAnalyzer>(source);
    }

    [Fact]
    public async Task STR0010_AllowsNullableAndDefaultValues()
    {
        var source = @"
class C
{
    public void M(string? value = null)
    {
    }
}
";

        await AnalyzerTestUtilities.VerifyAnalyzerAsync<Str0010MissingArgumentValidationAnalyzer>(source);
    }

    [Fact]
    public async Task STR0010_SkipsTestAssemblies()
    {
        // This code would normally trigger STR0010, but should be skipped
        // because the test assembly has xUnit references
        var source = @"
class C
{
    public void M(string value)
    {
    }
}
";

        // No diagnostics expected because this is a test assembly
        await AnalyzerTestUtilities.VerifyAnalyzerInTestAssemblyAsync<Str0010MissingArgumentValidationAnalyzer>(source);
    }
}
